# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded itrajcomp 1.0 [list source [file join $dir maingui.tcl]]\n[list source [file join $dir rmsd.tcl]]\n[list source [file join $dir utils.tcl]]\n[list source [file join $dir object.tcl]]\n[list source [file join $dir save.tcl]]\n[list source [file join $dir contacts.tcl]]\n[list source [file join $dir hbonds.tcl]]\n[list source [file join $dir gui.tcl]]\n[list source [file join $dir clustering.tcl]]\n[list source [file join $dir labels.tcl]]\n[list source [file join $dir covar.tcl]]
#\n[list source [file join $dir relrms.tcl]]
